adventurechallenge/Controllers/ChallengesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using adventurechallenge.Models;

namespace adventurechallenge.Controllers
{
    [Authorize]
    public class ChallengesController : Controller
    {
        private mijncontext db = new mijncontext();

        // GET: Challenges
        public ActionResult Index()
        {
            return View();
        }

        // GET: Challenges/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            return View(challenge);
        }

        // GET: Challenges/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Challenges/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ChallengeNummer,ChallengeBeschrijving,ChallengeMoeilijkheid,ChallengeKosten,ChallengeAantalMensen")] Challenge challenge)
        {
            if (ModelState.IsValid)
            {
                db.Challenges.Add(challenge);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(challenge);
        }

        // GET: Challenges/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            return View(challenge);
        }

        // POST: Challenges/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChallengeNummer,ChallengeBeschrijving,ChallengeMoeilijkheid,ChallengeKosten,ChallengeAantalMensen")] Challenge challenge)
        {
            if (ModelState.IsValid)
            {
                db.Entry(challenge).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(challenge);
        }

        // GET: Challenges/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            return View(challenge);
        }

        // POST: Challenges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Challenge challenge = db.Challenges.Find(id);
            db.Challenges.Remove(challenge);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

adventurechallenge/Controllers/gebruikersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using adventurechallenge.Models;

namespace adventurechallenge.Controllers
{
    public class gebruikersController : Controller
    {
        private mijncontext db = new mijncontext();

        // GET: gebruikers
        public ActionResult Index()
        {
            return View(db.gebruiker.ToList());
        }

        // GET: gebruikers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gebruiker gebruiker = db.gebruiker.Find(id);
            if (gebruiker == null)
            {
                return HttpNotFound();
            }
            return View(gebruiker);
        }

        // GET: gebruikers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: gebruikers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GebruikerId,GebruikerNaam,ChallengesVoltooid")] gebruiker gebruiker)
        {
            if (ModelState.IsValid)
            {
                db.gebruiker.Add(gebruiker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gebruiker);
        }

        // GET: gebruikers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gebruiker gebruiker = db.gebruiker.Find(id);
            if (gebruiker == null)
            {
                return HttpNotFound();
            }
            return View(gebruiker);
        }

        // POST: gebruikers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GebruikerId,GebruikerNaam,ChallengesVoltooid")] gebruiker gebruiker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gebruiker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gebruiker);
        }

        // GET: gebruikers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gebruiker gebruiker = db.gebruiker.Find(id);
            if (gebruiker == null)
            {
                return HttpNotFound();
            }
            return View(gebruiker);
        }

        // POST: gebruikers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            gebruiker gebruiker = db.gebruiker.Find(id);
            db.gebruiker.Remove(gebruiker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        adventure_challengeEntities entity = new adventure_challengeEntities();
        public ActionResult login()
        {
            return View();
        }
        public ActionResult signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(loginmodelview credentials)
        {
            bool userexist = entity.gebruiker.Any(x => x.GebruikerNaam == credentials.gebruikernaam && x.Wachtwoord == credentials.Wachtwoord);
            gebruiker u = entity.gebruiker.FirstOrDefault(x => x.GebruikerNaam == credentials.gebruikernaam && x.Wachtwoord == credentials.Wachtwoord);
            if(userexist)
            {
                FormsAuthentication.SetAuthCookie(u.GebruikerNaam, false);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "gebruikersnaam of wachtwoord is fout");
            return View();
        }
        [HttpPost]
        public ActionResult signup(gebruiker gebruikerinfo)
        {
            entity.gebruiker.Add(gebruikerinfo);
            entity.SaveChanges();
            return RedirectToAction("login");
        }
        public ActionResult signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("login");
        }
    }
}

adventurechallenge/Views/Shared/_Layout.cshtml
@{ 
    bool isloggedin = true;
    if(string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isloggedin = false;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Adventure Challenge", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @{
                        if (isloggedin)
                        {
                            <li>@Html.ActionLink("challenge", "Index", "Challenges")</li>
                            <li>@Html.ActionLink(User.Identity.Name, "Index", "Home")</li>
                            <li>@Html.ActionLink("signout", "signout", "gebruikers")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("login", "login", "gebruikers")</li>
                            <li>@Html.ActionLink("register", "signup", "gebruikers")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>